import os


API_V1 = "/api/v1"
DATABASE_URL = os.getenv("DATABASE_URL")
DATABASE_USERNAME = os.getenv("DATABASE_USERNAME")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_NAME = os.getenv("DATABASE_NAME")
USERNAME = os.getenv("IDEFIX_USER")
PASSWORD = os.getenv("IDEFIX_PASSWORD")
